### PR TITLE
removeDuplicate 加入python code

### PR DESCRIPTION
**Pull request by riederleeDEV**

### CODE REVIEW

**Comment by azl397985856** [comment]
这个python代码和我的js思路差异很大，以这种形式出现感觉不太合适

**Comment by azl397985856** [comment]
如果单纯地从多语言支持的角度看，这个是不合适的，因此除了语言不一样，思路也完全不一样。

建议这种可以提出你的解法，经过采纳之后，追加到原题目。

**Comment by riederleeDEV** [comment]
add python thought process and logical process to the removeDuplicateProblem. Sorry I just learned how to speak Chinese and if you guys have any question, feel free to reach me out. Thanks to Google Translate : D

**Comment by azl397985856** [comment]
> add python thought process and logical process to the removeDuplicateProblem. Sorry I just learned how to speak Chinese and if you guys have any question, feel free to reach me out. Thanks to Google Translate : D

我觉得不太好吧， 一个markdown里面两个相同的二级标题。 行文需要组织一下，建议二级标题不要新增了，直接穿插进去即可。

**Comment by riederleeDEV** [comment]
> > add python thought process and logical process to the removeDuplicateProblem. Sorry I just learned how to speak Chinese and if you guys have any question, feel free to reach me out. Thanks to Google Translate : D
> 
> 我觉得不太好吧， 一个markdown里面两个相同的二级标题。 行文需要组织一下，建议二级标题不要新增了，直接穿插进去即可。

Alright. So I will delete the subtitle. What do you think about the thought process? In other words, is the explanation fits your expectation?

**Comment by azl397985856** [comment]
> > > add python thought process and logical process to the removeDuplicateProblem. Sorry I just learned how to speak Chinese and if you guys have any question, feel free to reach me out. Thanks to Google Translate : D
> > 
> > 
> > 我觉得不太好吧， 一个markdown里面两个相同的二级标题。 行文需要组织一下，建议二级标题不要新增了，直接穿插进去即可。
> 
> Alright. So I will delete the subtitle. What do you think about the thought process? In other words, is the explanation fits your expectation?

yes, pretty good

**Comment by riederleeDEV** [comment]
Fix the issue :D Tell me if you have any problem

**Comment by azl397985856** [comment]
> Fix the issue :D Tell me if you have any problem

bit of  strange ....uhh    i wil give a demo for that. maybe tomorrow

**Comment by riederleeDEV** [comment]
add python solution to single Number algorithm problem

**Comment by azl397985856** [comment]
格式不对，参考下这个https://github.com/azl397985856/leetcode/pull/22

**Comment by riederleeDEV** [comment]
fix format problem. Add "Javascript" before the js code. Should be fine this time 👯

**Pull request closed without merging**
