### PR TITLE
two sum

### PR DESCRIPTION
**Pull request by kadambinipanda**

### CODE REVIEW

**Review by azl397985856 — CHANGES_REQUESTED** [review]
格式不正确， 请参考 https://github.com/azl397985856/leetcode/issues/363

**Review by kadambinipanda — COMMENTED** [review]
good

**Comment by kadambinipanda** [comment]
> 格式不正确， 请参考 #363

Can you translate this in English?

**Comment by azl397985856** [comment]
> > 格式不正确， 请参考 #363
> 
> Can you translate this in English?

incorrect format. plz refer #363

**Comment by kadambinipanda** [comment]
> > > 格式不正确， 请参考 #363
> > 
> > 
> > Can you translate this in English?
> 
> incorrect format. plz refer #363

okay

**Comment by azl397985856** [comment]
@kadambinipanda 

1. The code you post should run successfully in leetcode.com
2. if u want to contribute other programming language, you should add your code directly in the 
corresponding markdown file

**Pull request closed without merging**
