### PR TITLE
1.two sum.en.md

### PR DESCRIPTION
**Pull request by kadambinipanda**

### CODE REVIEW

**Comment by kadambinipanda** [comment]
I have executed this on leetcode and also put into the markdown file, but one of the checks fails, could you please help?

**Comment by azl397985856** [comment]
1. try not to add a new markdown file if there exists one.(also your file has no extension, so wired)
2. the format is not correct. 

a possible case:

代码支持：Python(this is the programming language you added), JS

Python Code(this is the programming language you added):


```py
// your code goes here
```

note: text inside the parentheses should **Not** be added

**Comment by kadambinipanda** [comment]
I updated the format as well added an extension.

**Comment by kadambinipanda** [comment]
@azl397985856  could you please tell me where I have gone wrong now?

**Comment by azl397985856** [comment]
> @azl397985856 could you please tell me where I have gone wrong now?

all wrong ~ （cry）

**Pull request closed without merging**
