### PR TITLE
fix: Update spelling mistakes in README.en.md

### PR DESCRIPTION
**Pull request by VusalIs**

### CODE REVIEW

**Comment by azl397985856** [comment]
👍 well done. Frankly speaking, the english version is far behind the chinese version.would u like to contribute the missing part? Hope u join us!

**Comment by VusalIs** [comment]
I have a similar repo for codeforces in my mother tongue, and I solve problems on that website, but If you translate the CONTRIBUTING.md file, I will try to contribute to this repo as well.

**Comment by azl397985856** [comment]
@VusalIs Got it. I'll do it right away!

**Comment by azl397985856** [comment]
@VusalIs https://github.com/azl397985856/leetcode/blob/master/CONTRIBUTING.en.md

**Pull request merged**
